export const SITE = {
  website: "https://phyjhh.github.io/",
  author: "phyj",
  profile: "https://github.com/phyjhh",
  desc: "My personal blog and portfolio.",
  title: "phyj",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 10,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Edit page",
    url: "https://github.com/phyjhh/phyjhh.github.io/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Shanghai",
} as const;
